package com.company.oop.logistics.commands;

public enum CommandType {
    CREATELOCATION,
    LISTLOCATIONS,
    CREATEROUTE,
    LISTROUTES,
    CREATETRUCK,
    ASSIGNVEHICLETOROUTE,
    CREATEDELIVERYPACKAGE,
    ASSIGNPACKAGE,
    FINDROUTESSERVICINGSTARTANDEND,
    CREATECUSTOMERCONTACTINFO,
    GETPACKAGESTATECOMMAND

}
